meal/urls.py
from django.urls import path

from . import views

app_name = 'meal'
urlpatterns = [
    path('', views.index, name='meals-list'),
    path('<int:id>/', views.detail, name='detail'),
    path('add/', views.addMeal, name='add-meal'),
    path('<int:id>/delete/', views.delete_meal, name='delete-meal'),
    path('<int:id>/update/', views.update_meal, name='update-meal'),
]

order/urls.py
from django.urls import path, re_path
from django.conf.urls import url

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    update_transaction_records,
    success
)

app_name = 'order'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^update-transaction/(?P<token>[-\w]+)/$', update_transaction_records,
        name='update_records')
]

warehouse/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('welcomePage.urls')),
    path('register/', include('register.urls')),
    path('address/', include('address.urls')),
    path('component/', include('component.urls')),
    path('customer/', include('customer.urls')),
    path('meal/', include('meal.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
]

order/models.py
from django.db import models
from shiping_method.models import ShippingMethod
from payment.models import Payment
from meal.models import Meal
from component.models import Component
from customer.models import Customer
from .signals import orderOrdered
from django.db.models.signals import post_save


class OrderMeal(models.Model):
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField(null=True)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)

    def increase_component_and_order_quantity(self):
        component_list = self.meal.components.all()
        self.meal.increase_meal_quantity()
        self.meal.save()
        for Component in component_list:
            Component.increase_component_amount()
            Component.save()
            
    def decrease_component_and_order_quantity(self):
        component_list = self.meal.components.all()
        self.meal.decrease_meal_quantity()
        self.meal.save()
        for Component in component_list:
            Component.decrease_component_amount()
            Component.save()

    def __str__(self):
        return self.meal.name


class Order(models.Model):
    order_date = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    meals = models.ManyToManyField(OrderMeal, null=True, blank=True)
    ref_code = models.CharField(max_length=15, null=True)
    is_ordered = models.BooleanField(default=False)
    shipping_method = models.ForeignKey(ShippingMethod, null=True, on_delete=models.SET_NULL)
    payment = models.OneToOneField(Payment, on_delete=models.PROTECT, null=True)

    def get_cart_products(self):
        return self.meals.all()

    def get_cart_total(self):
        return sum([meal.meal.price for meal in self.meals.all()])

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.order_date)


class Transaction(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    token = models.CharField(max_length=120)
    order_id = models.CharField(max_length=120)
    amount = models.DecimalField(max_digits=100, decimal_places=2)
    success = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.order_id

    class Meta:
        ordering = ['-timestamp']

order/views.py
from django.conf import settings
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from meal.models import Meal
from order.models import Order, Transaction, OrderMeal
from order.extras import generate_order_id, transact, generate_client_token
from customer.models import Customer
from meal.forms import MealForm

import datetime
import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY


def get_customer_pending_order(request):
    customer = get_object_or_404(Customer, user=request.user)
    order = Order.objects.filter(owner=customer, is_ordered=False)
    if order.exists():
        return order[0]
    return 0


@login_required
def add_to_cart(request, **kwargs):
    customer = get_object_or_404(Customer, user=request.user)
    meal = Meal.objects.filter(id=kwargs.get('item_id', "")).first()
    order_meal = OrderMeal.objects.create(meal=meal)

    if request.method == 'POST':
        form = MealForm(request.POST)

        if form.is_valid():
            order_meal.quantity = form.quantity
    else:
        form = MealForm()

    if meal.quantity !=0:
        order_meal.decrease_component_and_order_quantity()
        order_meal.save()
    else:
        messages.info(request, "Meal is out of stock !")
        return redirect(reverse('order:order_summary'), {'form': form})

    customer_order, status = Order.objects.get_or_create(owner=customer, is_ordered=False)
    customer_order.meals.add(order_meal)

    if status:
        customer_order.ref_code = generate_order_id()
        customer_order.save()

    customer.orders.add(customer_order)
    messages.info(request, "Meal added to cart")
    return redirect(reverse('order:order_summary'), {'form': form})


@login_required
def delete_from_cart(request, item_id):
    meal_to_delete = OrderMeal.objects.filter(pk=item_id).first()
    meal_to_delete.increase_component_and_order_quantity()

    if meal_to_delete:
        meal_to_delete.delete()
        messages.info(request,"Meal has been deleted from cart")

    return redirect(reverse('order:order_summary'))


@login_required
def order_details(request, **kwargs):
    existing_order = get_customer_pending_order(request)
    context = {
        'order': existing_order
    }
    return render(request, 'order_summary.html', context)


@login_required()
def checkout(request, **kwargs):
    customer_token = generate_client_token()
    existing_order = get_customer_pending_order(request)
    publish_key = settings.STRIPE_PUBLISHABLE_KEY
    if request.method == 'POST':
            result = transact({
                'amount': existing_order.get_cart_total(),
                'payment_method_nonce': request.POST['payment_method_nonce'],
                'options': {
                    "submit_for_settlement": True
                }
            })

            if result.is_success or result.transaction:
                return redirect(reverse('order:update_records',
                                        kwargs={
                                            'token': result.transaction.id
                                        })
                                )
            else:
                for x in result.errors.deep_errors:
                    messages.info(request, x)

                return redirect(reverse('order:checkout'))

    context = {
        'order': existing_order,
        'client_token': customer_token,
        'STRIPE_PUBLISHABLE_KEY': publish_key
    }

    return render(request, 'checkout.html', context)


@login_required
def update_transaction_records(request, token):
    order_to_purchase = get_customer_pending_order(request)
    customer_profile = get_object_or_404(Customer, user=request.user)

    order_to_purchase.is_ordered = True

    order_to_purchase.order_date = datetime.datetime.now()
    order_to_purchase.save()

    customer_profile.orders.add(order_to_purchase)

    customer_profile.save()

    transaction = Transaction(customer=request.user.customer,
                              token=token,
                              order_id=order_to_purchase.id,
                              amount=order_to_purchase.get_cart_total(),
                              success=True)
    transaction.save()

    messages.info(request, "Thank you! Your purchase was successfull !")
    return redirect('/customer/profile')


@login_required
def success(request, **kwargs):
    return render(request, 'order/purchase_success.html', {})

order/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Cart</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'footer.css' %}">

    {% block head %}{% endblock head %}
    {% block style %}{% endblock style %}

</head>
<body>
<nav class="navbar navbar-expand-xl navbar-dark bg-dark sticky-top">
    <a class="navbar-brand" href="/login/">
        <span style="font-size: 20px;">
        <i class="fas fa-warehouse"></i>
        </span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/login/">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/meal/">Menu<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/customer/profile/">History<span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="nav-item active">
                <a class="nav-link" href="/order/order-summary/">Cart<span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
    </nav>
<div>
    {% include 'messages.html' %}
    <div class="container">
        {% block content %}{% endblock content %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    {% block script %}{% endblock script %}
</div>

<div class="footer">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-1 mt-sm-1">
                        <ul class="list-inline text-center">
                        <li class="list-inline-item"><a href=""><i class="fab fa-facebook-square"></i></a></li>
                        <li class="list-inline-item"><a href=""><i class="fab fa-twitter-square"></i></a></li>
                        <li class="list-inline-item"><a href=""><i class="fab fa-instagram"></i></a></li>
                        <li class="list-inline-item"><a href=""><i class="fab fa-google-plus-square"></i></a></li>
                        </ul>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                    <ul class="menu list-inline custom-center">
                        <li class="list-inline-item">
                            <a href="/login/">Home</a>
                        </li>
                    </ul>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                    <p class="custom-center" style="color: white; margin-top: 10px">&copy Daniel Belter, Jędrzej Babło, Aleksander Kozyra 2018</p>
                    </div>
                </div>
            </div>
        </footer>
</div>
</body>
</html>

order/templates/checkout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Checkout</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <!--<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" type="text/css" rel="stylesheet">-->
    <link rel="stylesheet" href="{% static 'footer.css' %}">
    <style>
      #checkoutMethods {
        background: #fff;
        border-radius: 2px;
        display: inline-block;
        max-height: 700px;
        margin: 1rem;
        position: relative;
        width: 700px;
        box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);
      }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-xl navbar-dark bg-dark sticky-top">
    <a class="navbar-brand" href="/login/">
        <span style="font-size: 20px;">
        <i class="fas fa-warehouse"></i>
        </span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/login/">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/meal/">Menu<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="">History<span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="nav-item active">
                <a class="nav-link" href="">Cart<span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
    </nav>
<div>
    {% include 'messages.html' %}
    <br>
      <div class="col-md-8 col-xs-12">
        <table class="table">
          <tr>
            <td><h4>Order Summary</h4></td>
          </tr>
          <tr>
            <td>
              {% for item in order.get_cart_products %}
                <tr>
                  <td>{{ item }}</td>
                  <td>${{ item.meal.price }}</td>
                </tr>
              {% endfor %}
          <tr>
            <td><strong>Order Total</strong> </td>
            <td> <strong>${{ order.get_cart_total }}</strong></td>
          </tr>
        </table>
        <button onclick="toggleDisplay();" class="btn btn-warning" style="width: 100%;">Checkout with a credit card</button>
      </div>
</div>

<div id="collapseStripe" class="wrapper">
  <script src="https://js.stripe.com/v3/"></script>

  <form action="." method="post" id="payment-form">
    {% csrf_token %}
    <div id="checkoutMethods">
      <div style="margin: 10px;">
        <h2>Checkout!</h2>
        <div id="bt-dropin"></div>
        <div class="form-row">
          <!-- Used to display form errors. -->
          <div id="card-errors" role="alert"></div>
        </div>
        <input type="hidden" id="nonce" name="payment_method_nonce" />
      </div>
    </div>
    <button>Submit Payment</button>
  </form>
  </div>

<!-- script for the stripe form -->
<script src="{% static 'js/checkout.js' %}"></script>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<script src="https://js.braintreegateway.com/web/dropin/1.13.0/js/dropin.min.js"></script>
<script>
  var form = document.querySelector('#payment-form');
  var client_token = '{{ client_token }}';
  braintree.dropin.create({
    authorization: client_token,
    container: '#bt-dropin',
    paypal: {
      flow: 'vault'
    }
  }, function (createErr, instance) {
    form.addEventListener('submit', function (event) {
      event.preventDefault();
      instance.requestPaymentMethod(function (err, payload) {
        if (err) {
          console.log('Error', err);
          return;
        }
        // Add the nonce to the form and submit
        document.querySelector('#nonce').value = payload.nonce;
        form.submit();
      });
    });
  });
</script>

<!-- script for toggling display of the form -->
<script type="text/javascript">
    function toggleDisplay() {
      var x = document.getElementById("collapseStripe");
      if (x.style.display === "none") {
          x.style.display = "block";
      } else {
          x.style.display = "none";
      }
    };
</script>
<br><br><br>
<div class="footer">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-1 mt-sm-1">
                        <ul class="list-inline text-center">
                        <li class="list-inline-item"><a href=""><i class="fab fa-facebook-square"></i></a></li>
                        <li class="list-inline-item"><a href=""><i class="fab fa-twitter-square"></i></a></li>
                        <li class="list-inline-item"><a href=""><i class="fab fa-instagram"></i></a></li>
                        <li class="list-inline-item"><a href=""><i class="fab fa-google-plus-square"></i></a></li>
                        </ul>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                    <ul class="menu list-inline custom-center">
                        <li class="list-inline-item">
                            <a href="/">Home</a>
                        </li>
                    </ul>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                    <p class="custom-center" style="color: white; margin-top: 10px">&copy Daniel Belter, Jędrzej Babło, Aleksander Kozyra 2018</p>
                    </div>
                </div>
            </div>
        </footer>
</div>
</body>
</html>

order/templates/messages.html
{% if messages %}

 	<style type="text/css">
 		div.messages{
 			background-color: #ff6b6b;
 			color: #f7fff7;
 		}
 		ul.messages{
 			list-style-type: none;
 		}
 	</style>

    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li>{% if message.tags %} {% endif %}{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

order/templates/order_summary.html
{% extends "base.html" %}

{% block content %}
<br>
 <section>
   <div class="row">
    <table class="table table-hover table-bordered text-center">
      <tr class="text-center">
        <th>no.</th>
        <th>Item</th>
        <th>Price</th>
      </tr>
      {% for item in order.get_cart_products %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>
            {{ item.meal.name }}
            <span class="pull-right">
              <a href="{% url 'order:delete_item' item.id %}" data-balloon="remove this item from cart" class="text-danger" onclick="return confirm_delete();">
                <i class="fas fa-trash"></i>
              </a>
            </span>
          </td>
          <td>{{ item.meal.price }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan= 3> You have not added any items yet.</td>
        </tr>
      {% endfor %}
      <tr>
        {% if order.get_cart_total != None %}
        <td colspan=2>
          <strong class="pull-right">Order Total:</strong>
        </td>

        <td colspan= 1>
          $<strong>{{ order.get_cart_total }}</strong>
        </td>
        {% endif %}
      </tr>
      <tr>
        <td colspan=1 >
          <a href="{% url 'meal:meals-list' %}" class="btn btn-warning pull-left">
            {% if order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
          </a>
        </td>
        <td colspan=2>
          {% if order.get_cart_products %}
            <a href="{% url 'order:checkout' %}" class="pull-right btn btn-primary">Proceed To Checkout</a>
          {% endif %}
        </td>
      </tr>
    </table>
     
   </div>
 </section>
{% endblock %}

{% block scripts %}
  {{ block.super }}
  <script>
  function confirm_delete(){
    return confirm("Do you want to remove this item from cart?");
  }
  </script>
{% endblock scripts %}

order/templates/purchase_success.html
{% extends 'base.html' %}

{% block content %}
    <h1>Thank you for your purchase!</h1>
    <a href="{% url 'products:product-list' %}">Head back home</a>
{% endblock content %}

order/templates/stripe_default_form.html
<script src="https://js.stripe.com/v3/"></script>

<form action="." method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="{{ STRIPE_PUBLISHABLE_KEY }}"
    data-amount="999"
    data-name="Justdjango"
    data-description="Example charge"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto">
  </script>
</form>