meal/urls.py
from django.urls import path

from . import views

app_name = 'meal'
urlpatterns = [
    path('', views.index, name='meals-list'),
    path('<int:id>/', views.detail, name='detail'),
    path('add/', views.addMeal, name='add-meal'),
    path('<int:id>/delete/', views.delete_meal, name='delete-meal'),
    path('<int:id>/update/', views.update_meal, name='update-meal'),
]

order/urls.py
from django.urls import path, re_path
from django.conf.urls import url

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    update_transaction_records,
    success
)

app_name = 'order'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^update-transaction/(?P<token>[-\w]+)/$', update_transaction_records,
        name='update_records')
]

warehouse/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('welcomePage.urls')),
    path('register/', include('register.urls')),
    path('address/', include('address.urls')),
    path('component/', include('component.urls')),
    path('customer/', include('customer.urls')),
    path('meal/', include('meal.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
]

meal/models.py
from django.db import models
from component.models import Component
from django.core.validators import MinValueValidator

TYPE_OF_MEAL = (
    ('SOUP', 'SOUP'),
    ('PIZZA', 'PIZZA'),
    ('FISH', 'FISH'),
    ('BURGER', 'BURGER'),
    ('OTHER', 'OTHER'),
)


class Meal(models.Model):
    components = models.ManyToManyField(Component)
    name = models.CharField(max_length=30)
    price = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True,validators=[MinValueValidator(1)])
    meal_type = models.CharField(max_length=8, choices=TYPE_OF_MEAL)
    quantity = models.IntegerField(validators=[MinValueValidator(1)])
    description = models.ImageField(null=True, blank=True)

    def decrease_meal_quantity(self):
        self.quantity -= 1

    def increase_meal_quantity(self):
        self.quantity += 1
        
    def __str__(self):
        return self.name

meal/forms.py
from django import forms
from .models import Meal


class MealForm(forms.ModelForm):
    class Meta:
        model = Meal
        fields = ['components', 'name', 'price', 'meal_type', 'quantity', 'description']

    def __init__(self, *args, **kwargs):
        super(MealForm, self).__init__(*args, **kwargs)
        self.fields['price'].widget.attrs['min'] = 1
        self.fields['quantity'].widget.attrs['min'] = 1

meal/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.http import HttpResponse
from .models import Meal
from .decorators import group_required
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.http import HttpResponse
from .models import Meal
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from google.cloud import storage
from component.forms import ComponentForm
from meal.forms import MealForm


def index(request):
    meals = Meal.objects.order_by('-name').all()
    context = {'meals': meals, }
    return HttpResponse(render(request, 'meal/index.html', context))


def detail(request, id):
    meal = get_object_or_404(Meal, pk=id)
    if request.user.groups.filter(name='pracownik').exists():
        return render(request, 'meal/detail.html', {
            'meal': meal,
            'meal_fields': meal._meta.get_fields()
        })
    else:
        return render(request, 'meal/detailMealUser.html', {
            'meal': meal,
            'meal_fields': meal._meta.get_fields()
        })

@group_required('pracownik')
def update_meal(request, id):
    meal = get_object_or_404(Meal, pk=id)
    formMeal = MealForm()
    formComponent = ComponentForm()


    if request.method == 'POST':
        if 'authorFormButton' in request.POST:
            form = ComponentForm(request.POST)
            if form.is_valid():
                component = form.save()
                return render(request, 'meal/updateMeal.html', {'formComponent': formComponent, 'formMeal': formMeal})
            else:
                return render(request, 'meal/updateMeal.html', {'formComponent': form, 'formMeal': formMeal})
        elif 'mealButton' in request.POST:
            form = MealForm(request.POST, request.FILES, instance=meal)
            if form.is_valid():
                meal = form.save()
                testurl = meal.description
                return render(request, 'meal/updateMeal.html',
                              {'formComponent': formComponent, 'formMeal': formMeal, 'testurl': testurl})
            else:
                return render(request, 'meal/updateMeal.html', {'formComponent': form, 'formComponent': formComponent})
    else:
        return render(request, 'meal/updateMeal.html', {'formComponent': formComponent, 'formMeal': formMeal})


@group_required('pracownik')
def delete_meal(request, id):
    meal = get_object_or_404(Meal, pk=id)
    meal.delete()
    messages.info(request, "Meal has been deleted")
    return redirect('/meal/')


@group_required('pracownik')
def addMeal(request):
    formComponent = ComponentForm()
    formMeal = MealForm()

    if request.method == 'POST':
        if 'authorFormButton' in request.POST:
            form = ComponentForm(request.POST)
            if form.is_valid():
                component = form.save()
                return render(request, 'meal/pracAddMeal.html', {'formComponent': formComponent, 'formMeal': formMeal})
            else:
                return render(request, 'meal/pracAddMeal.html', {'formComponent': form, 'formMeal': formMeal})
        elif 'mealButton' in request.POST:
            form = MealForm(request.POST, request.FILES)
            if form.is_valid():
                meal = form.save()
                testurl = meal.description
                return render(request, 'meal/pracAddMeal.html',
                              {'formComponent': formComponent, 'formMeal': formMeal, 'testurl': testurl})
            else:
                return render(request, 'meal/pracAddMeal.html', {'formComponent': form, 'formComponent': formComponent})
    else:
        return render(request, 'meal/pracAddMeal.html', {'formComponent': formComponent, 'formMeal': formMeal})

meal/templates/meal/detail.html
<!doctype html>
<html lang="en">
<head>
    {% load staticfiles %}

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'footer.css' %}">
    <title>meal</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
<nav class="navbar navbar-expand-xl navbar-dark bg-dark sticky-top">
    <a class="navbar-brand" href="/login/">
        <span style="font-size: 20px;">
        <i class="fas fa-warehouse"></i>
        </span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/login/">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/meal/">Menu<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/customer/profile/">History<span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="nav-item active">
                <a class="nav-link" href="/order/order-summary/">Cart<span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
    </nav>
<br>
<h5><span style="padding-left: 10px">Name: {{ meal.name }}</span></h5>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<h5><span style="padding-left: 10px">Components: </span></h5>
{% for component in meal.components.all %}
    <ul>
        <li>{{ component.name }}</li>
    </ul>
{% endfor %}
<h5><span style="padding-left: 10px">Price: {{ meal.price }}</span></h5>
<h5><span style="padding-left: 10px">Quantity: {{ meal.quantity }}</span></h5>
<h5><span style="padding-left: 10px">Type: {{ meal.meal_type }}</span></h5>
             <img height="250" width="250"
             src='https://storage.googleapis.com/solwit-pjatk-arc-2018-gr2.appspot.com/{{ meal.description}}'
             alt="{{ meal.description}}"/>

<form action="{% url 'order:add_to_cart' meal.id %}" method="post">
    {% csrf_token %}
    {{ form }}
</form>
<span style="padding-left: 10px"><a href="{% url 'order:add_to_cart' meal.id %}" class="btn btn-primary">
    Add to cart
</a></span>
<a href="{% url 'order:order_summary'  %}" class="btn btn-success">
    Go to cart
</a>
<a href="{% url 'meal:delete-meal' meal.id %}"><span style="padding-left: 10px"><button  class="btn btn-danger">
    Delete the meal</button></span>
</a>

<a href="{% url 'meal:update-meal' meal.id%}"><button class="btn btn-warning">
    Change the meal</button>
</a>

<div class="footer">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-1 mt-sm-1">
                        <ul class="list-inline text-center">
                        <li class="list-inline-item"><a href=""><i class="fab fa-facebook-square"></i></a></li>
                        <li class="list-inline-item"><a href=""><i class="fab fa-twitter-square"></i></a></li>
                        <li class="list-inline-item"><a href=""><i class="fab fa-instagram"></i></a></li>
                        <li class="list-inline-item"><a href=""><i class="fab fa-google-plus-square"></i></a></li>
                        </ul>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                    <ul class="menu list-inline custom-center">
                        <li class="list-inline-item">
                            <a href="/login/">Home</a>
                        </li>
                    </ul>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                    <p class="custom-center" style="color: white; margin-top: 10px">&copy Daniel Belter, Jędrzej Babło, Aleksander Kozyra 2018</p>
                    </div>
                </div>
            </div>
        </footer>
</div>
</body>
</html>

meal/templates/meal/detailMealUser.html
<!doctype html>
<html lang="en">
<head>
    {% load staticfiles %}

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'footer.css' %}">
    <title>meal</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
<nav class="navbar navbar-expand-xl navbar-dark bg-dark sticky-top">
    <a class="navbar-brand" href="/login/">
        <span style="font-size: 20px;">
        <i class="fas fa-warehouse"></i>
        </span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/login/">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/meal/">Menu<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/customer/profile/">History<span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="nav-item active">
                <a class="nav-link" href="/order/order-summary/">Cart<span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
    </nav>
<br>
<h5><span style="padding-left: 10px">Name: {{ meal.name }}</span></h5>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<h5><span style="padding-left: 10px">Components: </span></h5>
{% for component in meal.components.all %}
    <ul>
        <li>{{ component.name }}</li>
    </ul>
{% endfor %}
<h5><span style="padding-left: 10px">Price: {{ meal.price }}</span></h5>
<h5><span style="padding-left: 10px">Quantity: {{ meal.quantity }}</span></h5>
<h5><span style="padding-left: 10px">Type: {{ meal.meal_type }}</span></h5>
             <img height="250" width="250"
             src='https://storage.googleapis.com/solwit-pjatk-arc-2018-gr2.appspot.com/{{ meal.description}}'
             alt="{{ meal.description}}"/>

<form action="{% url 'order:add_to_cart' meal.id %}" method="post">
    {% csrf_token %}
    {{ form }}
</form>
<span style="padding-left: 10px"><a href="{% url 'order:add_to_cart' meal.id %}" class="btn btn-primary">
    Add to cart
</a></span>
<a href="{% url 'order:order_summary'  %}" class="btn btn-success">
    Go to cart
</a>
<div class="footer">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-1 mt-sm-1">
                        <ul class="list-inline text-center">
                        <li class="list-inline-item"><a href=""><i class="fab fa-facebook-square"></i></a></li>
                        <li class="list-inline-item"><a href=""><i class="fab fa-twitter-square"></i></a></li>
                        <li class="list-inline-item"><a href=""><i class="fab fa-instagram"></i></a></li>
                        <li class="list-inline-item"><a href=""><i class="fab fa-google-plus-square"></i></a></li>
                        </ul>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                    <ul class="menu list-inline custom-center">
                        <li class="list-inline-item">
                            <a href="/login/">Home</a>
                        </li>
                    </ul>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                    <p class="custom-center" style="color: white; margin-top: 10px">&copy Daniel Belter, Jędrzej Babło, Aleksander Kozyra 2018</p>
                    </div>
                </div>
            </div>
        </footer>
</div>
</body>
</html>

meal/templates/meal/index.html
<!doctype html>
<html lang="en">
<head>
    {% load staticfiles %}

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'footer.css' %}">
    <title>meal</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-xl navbar-dark bg-dark sticky-top">
    <a class="navbar-brand" href="/login/">
        <span style="font-size: 20px;">
        <i class="fas fa-warehouse"></i>
        </span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/login/">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/meal/">Menu<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/customer/profile/">History<span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="nav-item active">
                <a class="nav-link" href="/order/order-summary/">Cart<span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
    </nav>
<br>
{% if meals %}
    <ul>
        {%  for meal in meals %}
            <li><a href="{% url 'meal:detail' meal.id %}"><button class="btn btn-dark">{{ meal.name }}</button></a>
                {% if meal.quantity == 0 %}
                <h3>OUT OF STOCK</h3>
                          <img height="250" width="250"
             src='https://storage.googleapis.com/solwit-pjatk-arc-2018-gr2.appspot.com/{{ meal.description}}'
             alt="{{ meal.description}}"/>
                {% else %}Quantity:
            {{ meal.quantity }}
            {% endif %}
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available</p>
{% endif %}

<div class="footer">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-1 mt-sm-1">
                        <ul class="list-inline text-center">
                        <li class="list-inline-item"><a href=""><i class="fab fa-facebook-square"></i></a></li>
                        <li class="list-inline-item"><a href=""><i class="fab fa-twitter-square"></i></a></li>
                        <li class="list-inline-item"><a href=""><i class="fab fa-instagram"></i></a></li>
                        <li class="list-inline-item"><a href=""><i class="fab fa-google-plus-square"></i></a></li>
                        </ul>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                    <ul class="menu list-inline custom-center">
                        <li class="list-inline-item">
                            <a href="/login/">Home</a>
                        </li>
                    </ul>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                    <p class="custom-center" style="color: white; margin-top: 10px">&copy Daniel Belter, Jędrzej Babło, Aleksander Kozyra 2018</p>
                    </div>
                </div>
            </div>
        </footer>
</div>
</body>
</html>

meal/templates/meal/pracAddMeal.html
<!doctype html>
<html lang="pl">
<head>
    {% load staticfiles %}

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'footer.css' %}">
    <title>meal</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
<nav class="navbar navbar-expand-xl navbar-dark bg-dark sticky-top">
    <a class="navbar-brand" href="/login/">
        <span style="font-size: 20px;">
        <i class="fas fa-warehouse"></i>
        </span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/login/">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/meal/">Menu<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/customer/profile/">History<span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="nav-item active">
                <a class="nav-link" href="/order/order-summary/">Cart<span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
    </nav>


<div class="container">
    <div class="row">
        <div class="col-xl-8 offset-xl-2">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h1>{{ form.errors }}</h1>
                <div class="form-group">
                    <label for="name" class="h2 ">Component: </label>
                    <h3>{{ formMeal.components}}</h3>
                </div>
                <div class="form-group">
                    <label for="name" class="h2 ">Name:</label>
                    <h3>{{ formMeal.name }}</h3>
                </div>
                <div class="form-group">
                    <label for="name" class="h2 ">Price:</label>
                    <h3>{{ formMeal.price}}</h3>
                </div>
                <div class="form-group">
                    <label for="name" class="h2 ">Type:</label>
                    <h3>{{ formMeal.meal_type }}</h3>
                </div>
                <div class="form-group">
                    <label for="name" class="h2 ">Quantity:</label>
                    <h3>{{ formMeal.quantity }}</h3>
                </div>
                <div class="form-group">
                    <label for="name" class="h2 ">Picture:</label>
                    <h3>{{ formMeal.description}}</h3>
                </div>
                 <input type="submit" value="Submit" name="mealButton">
            </form>
        </div>
    </div>
</div>
<br><br><br><br>
    <div class="footer">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-1 mt-sm-1">
                        <ul class="list-inline text-center">
                        <li class="list-inline-item"><a href=""><i class="fab fa-facebook-square"></i></a></li>
                        <li class="list-inline-item"><a href=""><i class="fab fa-twitter-square"></i></a></li>
                        <li class="list-inline-item"><a href=""><i class="fab fa-instagram"></i></a></li>
                        <li class="list-inline-item"><a href=""><i class="fab fa-google-plus-square"></i></a></li>
                        </ul>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                    <ul class="menu list-inline custom-center">
                        <li class="list-inline-item">
                            <a href="/">Home</a>
                        </li>
                    </ul>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                    <p class="custom-center" style="color: white; margin-top: 10px">&copy Daniel Belter, Jędrzej Babło, Aleksander Kozyra 2018</p>
                    </div>
                </div>
            </div>
        </footer>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>